"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$character
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "color_orange"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "color_orange"
style_root = "color_red"
format = '[ $user ]($style)'

[directory]
style = "color_yellow"
format = "[$path ]($style)"
truncate_to_repo = true
read_only_style = "red"

[git_branch]
symbol = ""
style = "color_aqua"
format = '[[$symbol $branch ]($style)]($style)'

[git_status]
style = "color_aqua"
format = '[[($all_status$ahead_behind )](color_aqua)]($style)'

[nodejs]
symbol = ""
style = "color_blue"
format = '[$symbol]($style) '

[cmake]
symbol = ""
style = "color_blue"
format = '[$symbol]($style) '

[c]
symbol = ""
style = "color_blue"
format = '[$symbol]($style) '

[custom.cpp]
detect_extensions = ['cpp', 'cc', 'hpp']
symbol = "󰙲"
style = "color_blue"
format = '[$symbol]($style) '
disabled = false

[rust]
symbol = ""
style = "color_blue"
format = '[$symbol]($style) '

[golang]
symbol = ""
style = "color_blue"
format = '[$symbol]($style) '

[java]
symbol = ""
style = "color_blue"
format = '[$symbol]($style) '

[python]
symbol = ""
style = "color_blue"
format = '[$symbol]($style) '

[docker_context]
symbol = ""
style = "color_blue"
format = '[$symbol]($style) '

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
